package introduction.ExceptionHandling.tryCatch;

public class Main {
    public static void main(String[] args) {

        int[] a = new int[5];

        System.out.println("Hello, Guys");

//        try{
//
//            int result = 5/0;
//
//            System.out.println(a[8]);
//
//        } catch (ArrayIndexOutOfBoundsException e){
//            System.out.println("Tried to access the invalid index.");
//        } catch(ArithmeticException e){
//            System.out.println(e.getStackTrace());
//            System.out.println(e.getMessage());
//            System.out.println(e);
//        }

        try {

            int result = 5 / 0;

//            System.out.println("In middle of two exceptions.");

            System.out.println(a[8]);
        } // handle all exceptions at once:
            catch(Exception e){
            System.out.println("Handling the exception");
        }

//         catch(ArrayIndexOutOfBoundsException | ArithmeticException e){
//            System.out.println("Handling the exception");
//        } catch(RuntimeException e){
//            System.out.println("Handlinng the exception");
//        }

        System.out.println("Bye, Guys");

//        ArrayIndexOutOfBoundsException obj = new ArrayIndexOutOfBoundsException(2);
//
//        System.out.println(obj.getMessage());
//
//        System.out.println(obj);
//
//        System.out.println(obj.getClass());
    }
}
